server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost/volunteerplatform
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: scrumbledore.email@gmail.com
    password: Scrumb!3dor3
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

platformuser:
  roles:
    - ROLE_VOLUNTEER
    - ROLE_ORGANIZATION
    - ROLE_INDIVIDUAL
    - ROLE_ADMIN

apptree:
  actions:
    - |       # ROLE_VOLUNTEER
        *Profile
          Edit profile
          View my profile as seen by others

        *Search
          Search for organizations/individuals
          Find all activities
          Search and filter activities based on a text/criteria search

        *My activities
          Accept or deny invites
          Apply for activity
    - |       # ROLE_ORGANIZATION
        *Profile
          Edit profile
          View my profile as seen by others

        *Search
          Search for volunteers
          Find all Volunteers
          Search and filter volunteers based on a text/criteria search

        *My activities
          Create activity
          Get Own Activities
          Get Own Drafts
          Edit Own Draft
          Post Own Draft
          Send Invite to Volunteer
          Accept or deny applications
    - |       # ROLE_INDIVIDUAL
        *Profile
          Edit profile
          View my profile as seen by others

        *Search
          Search for volunteers
          Find all Volunteers
          Find Volunteers based on a text/criteria search

        *My activities
          Create activity
          Get Own Activities
          Get Own Drafts
          Edit Own Draft
          Post Own Draft
          Send Invite to Volunteer
          Accept or deny applications
scheduling:
  deleteresettoken: 0 0 0 ? * *