server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost/volunteerplatform
      auto-index-creation: true

platformuser:
  roles:
    - ROLE_VOLUNTEER
    - ROLE_ORGANIZATION
    - ROLE_INDIVIDUAL