###
// create regular user - change e-mail-address
POST http://localhost:9000/users
Content-Type: application/json

{
  "username": "RumbleDumble12",
  "password": "wizard",
  "role": ["ROLE_VOLUNTEER"],
  "fullname": "Albus Dumbledore",
  "dateOfBirth": "1980-10-10",
  "address": "Hogwarts",
  "email": "georg.sebastian.palla@gmail.com",
  "description": "You're a wizard, Harry!"
}

###
//reset password from wizard to magic
PUT http://localhost:9000/users/profile/password/reset/RumbleDumble12/magic

###
// new password not working before activated
GET http://localhost:9000/users/login
Authorization: Basic RumbleDumble12 magic

###
// new login - without clicking activation link + show database reset token (for 15 min), email, click link
GET http://localhost:9000/users/login
Authorization: Basic RumbleDumble12 magic

###
// old login
GET http://localhost:9000/users/login
Authorization: Basic RumbleDumble12 wizard

###
// new login
GET http://localhost:9000/users/login
Authorization: Basic RumbleDumble12 magic