###
// invite volunteer1
PUT http://localhost:9000/activity/---ID---/invite/Volunteer1
Authorization: Basic Individual1 individual

###
// accept invitation
PUT http://localhost:9000/activity/---ID---/accept
Authorization: Basic Volunteer1 volunteer

###
// complete activity as creator
PUT http://localhost:9000/activity/---ID---/complete
Authorization: Basic Individual1 individual
Content-Type: application/json

[
  {
    "username" : "Volunteer1",
    "rating" : 4,
    "feedback" : "awesome!"
  }
]

###
// complete activity as participant
PUT http://localhost:9000/activity/---ID---/close
Authorization: Basic Volunteer1 volunteer
Content-Type: application/json

{
  "username" : "Organization1",
  "rating" : 3,
  "feedback" : "quiet ok"
}

### (show filter after activity completion)
// search for cook as Organization
GET http://localhost:9000/search/volunteers/cook?filterSkills=cooking&filterRating=3
Authorization: Basic Organization1 organization

### (show filter after activity completion)
// search for cook as Organization no result
GET http://localhost:9000/search/volunteers/cook?filterSkills=cooking&filterRating=5
Authorization: Basic Organization1 organization