###
// change to draft
PUT http://localhost:9000/activity/---ID---/changeToDraft
Authorization: Basic Individual1 individual

###
// delete draft (or in progess without participants)
DELETE http://localhost:9000/activity/---ID---
Authorization: Basic Individual1 individual

###
// invite volunteer2
PUT http://localhost:9000/activity/2e62b2eb-5f90-4b54-a569-43cd84041557/invite/Volunteer2
Authorization: Basic Individual1 individual

###
// accept invitation
PUT http://localhost:9000/activity/2e62b2eb-5f90-4b54-a569-43cd84041557/accept
Authorization: Basic Volunteer2 volunteer


###
// delete in progress not possible
DELETE http://localhost:9000/activity/2e62b2eb-5f90-4b54-a569-43cd84041557
Authorization: Basic Individual1 individual
