###
// get own activities
GET http://localhost:9000/activity/
Authorization: Basic Organization1 organization

###
// invite volunteer1
PUT http://localhost:9000/activity/311cbcca-676b-4b26-9576-33c89d2c9592/invite/Volunteer2
Authorization: Basic Individual1 individual

###
// accept invitation
PUT http://localhost:9000/activity/311cbcca-676b-4b26-9576-33c89d2c9592/accept
Authorization: Basic Volunteer2 volunteer

###
// complete activity
PUT http://localhost:9000/activity/311cbcca-676b-4b26-9576-33c89d2c9592/complete
Authorization: Basic Individual1 individual
Content-Type: application/json

[
  {
    "username" : "Volunteer2",
    "rating" : 4,
    "feedback" : "toll gemacht"
  }
]


###
// complete activity
PUT http://localhost:9000/activity/311cbcca-676b-4b26-9576-33c89d2c9592/close
Authorization: Basic Volunteer2 volunteer
Content-Type: application/json

  {
    "username" : "Individual1",
    "rating" : 2,
    "feedback" : "wenn ich null Sterne geben könnte"
  }

