###
// delete activity
DELETE http://localhost:9000/activity/cb0ea1a8-add2-4b51-8ddb-7568581d07c7
Authorization: Basic Organization1 organization

###
// invite volunteer1
PUT http://localhost:9000/activity/cb0ea1a8-add2-4b51-8ddb-7568581d07c7/invite/Volunteer1
Authorization: Basic Organization1 organization

###
// accept invitation
PUT http://localhost:9000/activity/cb0ea1a8-add2-4b51-8ddb-7568581d07c7/accept
Authorization: Basic Volunteer1 volunteer

###
// change to draft
PUT http://localhost:9000/activity/cb0ea1a8-add2-4b51-8ddb-7568581d07c7/changeToDraft
Authorization: Basic Organization1 organization