###
// search
GET http://localhost:9000/search/activities/Quidditch
Authorization: Basic Volunteer1 volunteer

###
// get all own drafts
GET http://localhost:9000/activity/drafts/
Authorization: Basic Organization1 organization

###
// post first drafted activity
PUT http://localhost:9000/activity/drafts/b0c9e4d9-85df-41c1-9a44-08ace14a03f4/post
Authorization: Basic Organization1 organization

###
// get all own drafts
GET http://localhost:9000/activity/drafts/
Authorization: Basic Individual1 individual


###
// post first drafted activity
PUT http://localhost:9000/activity/drafts/155017d3-7207-4cb1-989a-366d964b032b/post
Authorization: Basic Individual1 individual


###
// search volunteer criteria
GET http://localhost:9000/search/volunteers/Quidditch
Authorization: Basic Organization1 organization

###
// search volunteer criteria
GET http://localhost:9000/search/volunteers/cook
Authorization: Basic Organization1 organization

###
// search volunteer criteria
GET http://localhost:9000/search/volunteers/cook/?filterSkills=fly
Authorization: Basic Organization1 organization

###
// search volunteer criteria
GET http://localhost:9000/search/volunteers/cook/?filterSkills=fly&filterRating=2
Authorization: Basic Organization1 organization

###
// search volunteer criteria
GET http://localhost:9000/search/volunteers/cook/?filterRating=2
Authorization: Basic Organization1 organization


###
// search activity as volunteer without filters
GET http://localhost:9000/search/activities/cook
Authorization: Basic Volunteer1 volunteer

###
// search activity as volunteer with filters
GET http://localhost:9000/search/activities/cook/?filterDate=2021-08-15&filterCategory=3&filterCreator=Indiv
Authorization: Basic Volunteer1 volunteer