###
// get all own drafts
GET http://localhost:9000/activity/drafts/
Authorization: Basic Organization1 organization

###
// edit one drafted activity
PUT http://localhost:9000/activity/drafts/f4bb559e-230b-41ed-aeb8-ce0fa5ab980a
Authorization: Basic Organization1 organization
Content-Type: application/json

{
  "title" : "Test Activity from Organization1",
  "description" : "test change",
  "startDate" : "2021-08-17T07:00"
}

###
// post first drafted activity
PUT http://localhost:9000/activity/drafts/f4bb559e-230b-41ed-aeb8-ce0fa5ab980a/post
Authorization: Basic Organization1 organization

###
// get all own drafts
GET http://localhost:9000/activity/drafts/
Authorization: Basic Organization1 organization

###
// post other drafted activity
PUT http://localhost:9000/activity/drafts/9a337b1d-50d3-462f-bd1e-25da3a7434e4/post
Authorization: Basic Organization1 organization