###
// apply for activity
PUT http://localhost:9000/activity/2ac73321-a4b0-4ef5-9185-085dbdb1664f/apply/
Authorization:  Basic Volunteer1 volunteer

###
// apply for activity
PUT http://localhost:9000/activity/280cf6f9-90cf-4fd0-a7d0-05044ffc3e4e/apply/
Authorization:  Basic Volunteer3 volunteer

