###
// apply for activity
PUT http://localhost:9000/activity/---IDÄNDERN---/apply/
Authorization:  Basic Volunteer1 volunteer

###
// apply for activity
PUT http://localhost:9000/activity/---IDÄNDERN---/apply/
Authorization:  Basic Volunteer2 volunteer

