###
// apply for activity
PUT http://localhost:9000/activity/4073991e-f65e-48f8-8723-0d8b55521e52/apply/
Authorization:  Basic Volunteer1 volunteer

###
// apply for activity
PUT http://localhost:9000/activity/4073991e-f65e-48f8-8723-0d8b55521e52/apply/
Authorization:  Basic Volunteer2 volunteer

