###
// accept volunteer1 for activity 1
PUT http://localhost:9000/activity/f4bb559e-230b-41ed-aeb8-ce0fa5ab980a/Volunteer1/accept
Authorization:  Basic Organization1 organization

###
// deny volunteer2 for activity 1 --- show MongoDB Volunteer2 and Volunteer1
PUT http://localhost:9000/activity/f4bb559e-230b-41ed-aeb8-ce0fa5ab980a/Volunteer2/deny
Authorization:  Basic Organization1 organization