###
// regular user - volunteer
POST http://localhost:9000/users
Content-Type: application/json

{
  "username": "Volunteer1",
  "password": "volunteer",
  "role": ["ROLE_VOLUNTEER"],
  "fullname": "Albus Dumbledore",
  "dateOfBirth": "1980-10-10",
  "address": "Hogwarts",
  "email": "volunteer1@hogwarts.com"
}

###
// regular user - organization
POST http://localhost:9000/users
Content-Type: application/json

{
  "username": "Organization3",
  "password": "organization",
  "role": ["ROLE_ORGANIZATION"],
  "fullname": "Albus Dumbledore",
  "dateOfBirth": "1980-10-10",
  "address": "Hogwarts",
  "email": "organization3@hogwarts.com"
}


###
// create new activity
POST http://localhost:9000/activity/
Authorization: Basic Organization3 organization
Content-Type: application/json

{
  "title" : "Test Activity2",
  "description" : "test activity",
  "startDate" : "2021-08-16T17:00"
}

###
// get all own drafts
GET http://localhost:9000/activity/drafts/
Authorization: Basic Organization3 organization

###
// post one drafted activity
PUT http://localhost:9000/activity/drafts/1ecb609e-44d4-4e01-b8f4-bf1c3a54a23a/post
Authorization: Basic Organization3 organization


###
// apply for activity
PUT http://localhost:9000/activity/1ecb609e-44d4-4e01-b8f4-bf1c3a54a23a/apply/
Authorization:  Basic Volunteer1 volunteer



###
// accept volunteer1 for activity
PUT http://localhost:9000/activity/1ecb609e-44d4-4e01-b8f4-bf1c3a54a23a/Volunteer1/accept
Authorization:  Basic Organization3 organization
