###
// regular user - individual
POST http://localhost:9000/users
Content-Type: application/json

{
  "username": "Individual1",
  "password": "individual",
  "role": ["ROLE_INDIVIDUAL"],
  "fullname": "Albus Dumbledore",
  "dateOfBirth": "1980-10-10",
  "address": "Hogwarts",
  "email": "individual1@hogwarts.com"
}

###
// post test notification
POST http://localhost:9000/notifications
Authorization: Basic Individual1 individual

###
GET http://localhost:9000/notifications
Authorization: Basic Individual1 individual

