###
// apply for activity
PUT http://localhost:9000/activity/249d5ce8-bb9d-43db-9e96-300f1cbfe255/apply/
Authorization:  Basic Volunteer1 volunteer

###
// withdraw for activity
PUT http://localhost:9000/activity/249d5ce8-bb9d-43db-9e96-300f1cbfe255/withdraw/
Authorization:  Basic Volunteer1 volunteer



###
// apply for activity
PUT http://localhost:9000/activity/249d5ce8-bb9d-43db-9e96-300f1cbfe255/apply/
Authorization:  Basic Volunteer1 volunteer

###
// accept volunteer1 for activity 1
PUT http://localhost:9000/activity/249d5ce8-bb9d-43db-9e96-300f1cbfe255/Volunteer1/accept
Authorization:  Basic Organization1 organization

###
// withdraw for activity
PUT http://localhost:9000/activity/249d5ce8-bb9d-43db-9e96-300f1cbfe255/withdraw/
Authorization:  Basic Volunteer1 volunteer