###
// apply for activity
PUT http://localhost:9000/activity/9e8e1e29-282f-40df-85dc-ba6d84aac1ef/apply/
Authorization:  Basic Volunteer1 volunteer

###
// withdraw for activity
PUT http://localhost:9000/activity/9e8e1e29-282f-40df-85dc-ba6d84aac1ef/withdraw/
Authorization:  Basic Volunteer1 volunteer


###
// apply for activity
PUT http://localhost:9000/activity/9e8e1e29-282f-40df-85dc-ba6d84aac1ef/apply/
Authorization:  Basic Volunteer1 volunteer

###
// accept volunteer1 for activity 1
PUT http://localhost:9000/activity/9e8e1e29-282f-40df-85dc-ba6d84aac1ef/Volunteer1/accept
Authorization:  Basic Organization1 organization

###
// withdraw for activity
PUT http://localhost:9000/activity/9e8e1e29-282f-40df-85dc-ba6d84aac1ef/withdraw/
Authorization:  Basic Volunteer1 volunteer
